- type: jobWeight
  id: SunriseJobWeight
  weights:
    CargoTechnician: 0
    Quartermaster: 40
    SalvageSpecialist: 10
    CBURN: 0
    DeathSquad: 0
    ERTLeader: 0
    ERTChaplain: 0
    ERTEngineer: 0
    ERTSecurity: 0
    ERTMedical: 0
    ERTJanitor: 0
    CentralCommandOfficial: 0
    Passenger: 0
    Bartender: 0
    Botanist: 0
    Chaplain: 0
    Chef: 0
    Clown: 0
    Janitor: 0
    Lawyer: 0
    Librarian: 0
    Mime: 0
    Musician: 0
    ServiceWorker: 0
    Visitor: 0
    Captain: 100
    HeadOfPersonnel: 90
    AtmosphericTechnician: 20
    ChiefEngineer: 70
    StationEngineer: 10
    TechnicalAssistant: 0
    Chemist: 30
    ChiefMedicalOfficer: 60
    MedicalDoctor: 20
    MedicalIntern: 0
    Paramedic: 25
    StationAi: 10
    Borg: -10
    ResearchAssistant: 0
    ResearchDirector: 50
    Scientist: 10
    Detective: 20
    HeadOfSecurity: 80
    SecurityCadet: 0
    SecurityOfficer: 10
    Warden: 70
    Psychologist: 10
    Reporter: 0
    TramDriver: 0
    BlueShieldEnsign: 0
    BlueShieldOfficer: 0
    MailCarrier: 30
    MiningSpecialist: 0
    BlueShieldOperative: 0
    CBURNAgentEVA: 0
    CBURNLeader: 0
    CentCommOfficial: 30
    CentCommOperator: 30
    NtrLeader: 0
    NtrGuard: 0
    Barber: 0
    Adjutant: 0
    ComMaid: 0
    NanoTrasenRepresentative: 0
    SeniorEngineer: 30
    IAA: 40
    Magistrat: 75
    NtrOfficer: 40
    MedicalPathologist: 0
    SeniorPhysician: 35
    HeadOfPrison: 100
    PlanetPrisoner: 10
    PrisonChef: 40
    PrisonDoctor: 50
    PrisonEngineer: 70
    PrisonInspector: 90
    PrisonPilot: 80
    PrisonScientist: 60
    PrisonTrainee: 15
    PrisonWorker: 80
    Roboticist: 30
    SeniorResearcher: 35
    Brigmedic: 15
    SecurityPilot: 50
    SeniorOfficer: 60
    ClownBorg: -10
    EngineerBorg: -10
    JanitorBorg: -10
    MedicalBorg: -10
    MiningBorg: -10
    PeaceBorg: -10
    SecurityBorg: -10
    ServiceBorg: -10
    TSFMarine: 0
    USSPCrew: 0
    USSPOfficer: 0
    USSPOfficerAlt: 0
    USSPSoldier: 0
    USSPCaptain: 0
