- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    # Sunrise added start - ограничение расы для должности
    - !type:SpeciesRequirement
      species: [Vox]
      inverted: true
    # Sunrise added end
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 1h
