using System.Globalization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Communications.UI.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RelayControls : BoxContainer
{
    public event Action? OnToggleRelay;

    public RelayControls()
    {
        RobustXamlLoader.Load(this);
        RelayButton.OnPressed += _ => OnToggleRelay?.Invoke();
    }

    public void UpdateState(bool canRelay, bool isRelaying, float cooldownRemaining, float relayTimeRemaining)
    {
        RelayButton.Disabled = !canRelay && !isRelaying;

        if (isRelaying)
        {
            RelayButton.Text = Loc.GetString("comms-console-menu-relay-stop");
            RelayStatusLabel.Text = Loc.GetString("comms-console-menu-relay-time-left",
                ("time", FormatTime(relayTimeRemaining)));
            RelayStatusLabel.Visible = true;
            return;
        }

        RelayButton.Text = Loc.GetString("comms-console-menu-relay-button");
        if (cooldownRemaining > 0f)
        {
            RelayButton.Disabled = true;
            RelayStatusLabel.Text = Loc.GetString("comms-console-menu-relay-cooldown",
                ("time", FormatTime(cooldownRemaining)));
            RelayStatusLabel.Visible = true;
            return;
        }

        RelayStatusLabel.Text = string.Empty;
        RelayStatusLabel.Visible = false;
    }

    private static string FormatTime(float seconds)
    {
        return TimeSpan.FromSeconds(Math.Max(0f, seconds)).ToString(@"mm\:ss", CultureInfo.CurrentCulture);
    }
}
